### ISSUE TITLE
luci fails if login as root

### ISSUE THREAD

**Issue by Juul** [sudomesh/luci-app-peopleswifi#1]
From the command line try:

REQUEST_URI="/cgi-bin/luci HTTP/1.1" QUERY_STRING="username=root&password=<root_password>" /www/cgi-bin/luci

luci produces no output

**Comment by Juul** [comment]
I found the problem. The main authenticator used by luci is called authenticator.htmlauth. It is responsible for the "wrong username or password" page. It does not check if the user is in the list of allowed users, but that is checked later anyway and so the request is not allowed and no output is produced. Only the function authenticator.htmlauth in the file /usr/lib/lua/luci/dispatcher.lua needs to be changed. The updated function looks like this:

```
function authenticator.htmlauth(validator, accs, default)                                            
        local user = luci.http.formvalue("username")                                              
        local pass = luci.http.formvalue("password")                                              

        if user and validator(user, pass) and util.contains(accs, user) then
                return user                                                   
        end                                                                 

        require("luci.i18n")                                                
        require("luci.template")                                                   
        context.path = {}                                                                 
        luci.template.render("sysauth", {duser=default, fuser=user})        
        return false                                                       
end
```

Unfortunately, this means we have to patch luci itself

**Comment by max-b** [comment]
I tried submitting a patch at http://luci.subsignal.org/trac/newticket but their captcha system is broken and is just rejecting all submissions....

I emailed one of the devs and I'm hoping to hear something back I guess.

**Comment by jhpoelen** [comment]
No longer an issue - we are able to login using the home node web admin.
