### ISSUE TITLE
Improve Internet Bandwidth Sharing Interface

### ISSUE THREAD

**Issue by wrought** [sudomesh/luci-app-peopleswifi#9]
## Feature

While speaking with the LAmeshnet folks yesterday, Daniel had a really good idea to help end users know how many users can be supported when they share a selected percentage of their upload and download bandwidth. This could be built on top of Marc's suggestion of also probing the network in order to make a recommendation to the user, based on the performance speed at that moment. I am also curious if there is some way to perform such testing regularly, or even on-the-fly. E.g. probe every hour, and update if the change fits in a tolerance? It's unclear, but I think heuristics **could** be used, but that's far off.

I made some mock-ups of what this could look like:
### Landing on the page

![share_an_internet_connection_1](https://cloud.githubusercontent.com/assets/764063/2950247/7975bb1e-da18-11e3-89eb-c128eede73d9.png)
### Select "Test bandwidth" button

![share_an_internet_connection_2](https://cloud.githubusercontent.com/assets/764063/2950248/79766b72-da18-11e3-8122-6db3e13184d7.png)
### @TODO
- Decide how to represent / scale the number of users based on selected upload/download speeds (the math).
- Decide recommendation algorithm for internet sharing.
  - Could maybe scope this based on use case, or user-submitted data
    - For instance, there could be options for "in the home" or "at the office" or "in a public place"
    - Perhaps this should be informed by data.
- **_Question:**_ Are we able to aggregate or detect any data of how much users are sharing? 
- Implement math functions
- Implement interface similar to as depicted above

**Comment by wrought** [comment]
Made a wiki page for all mockups in the future:

https://sudoroom.org/wiki/Mesh/Mockups

**Comment by wrought** [comment]
This library may help for setting up Luci / bootstrap compatible sliders: http://www.eyecon.ro/bootstrap-slider/

**Comment by wrought** [comment]
This may require changes for node interface, node firmware, and node server in order to set arbitrary values (e.g. up to 1 or 2 decimal points).

**Comment by paidforby** [comment]
app no longer used
